// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/a10adotapp/a10a.app/ent/changokushiweapon"
	"github.com/a10adotapp/a10a.app/ent/changokushiweaponchangelog"
	"github.com/a10adotapp/a10a.app/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	changokushiweaponMixin := schema.ChangokushiWeapon{}.Mixin()
	changokushiweaponMixinHooks1 := changokushiweaponMixin[1].Hooks()
	changokushiweapon.Hooks[0] = changokushiweaponMixinHooks1[0]
	changokushiweaponMixinInters1 := changokushiweaponMixin[1].Interceptors()
	changokushiweapon.Interceptors[0] = changokushiweaponMixinInters1[0]
	changokushiweaponMixinFields0 := changokushiweaponMixin[0].Fields()
	_ = changokushiweaponMixinFields0
	changokushiweaponFields := schema.ChangokushiWeapon{}.Fields()
	_ = changokushiweaponFields
	// changokushiweaponDescCreatedAt is the schema descriptor for created_at field.
	changokushiweaponDescCreatedAt := changokushiweaponMixinFields0[0].Descriptor()
	// changokushiweapon.DefaultCreatedAt holds the default value on creation for the created_at field.
	changokushiweapon.DefaultCreatedAt = changokushiweaponDescCreatedAt.Default.(func() time.Time)
	// changokushiweaponDescUpdatedAt is the schema descriptor for updated_at field.
	changokushiweaponDescUpdatedAt := changokushiweaponMixinFields0[1].Descriptor()
	// changokushiweapon.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	changokushiweapon.DefaultUpdatedAt = changokushiweaponDescUpdatedAt.Default.(func() time.Time)
	// changokushiweapon.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	changokushiweapon.UpdateDefaultUpdatedAt = changokushiweaponDescUpdatedAt.UpdateDefault.(func() time.Time)
	changokushiweaponchangelogMixin := schema.ChangokushiWeaponChangeLog{}.Mixin()
	changokushiweaponchangelogMixinHooks1 := changokushiweaponchangelogMixin[1].Hooks()
	changokushiweaponchangelog.Hooks[0] = changokushiweaponchangelogMixinHooks1[0]
	changokushiweaponchangelogMixinInters1 := changokushiweaponchangelogMixin[1].Interceptors()
	changokushiweaponchangelog.Interceptors[0] = changokushiweaponchangelogMixinInters1[0]
	changokushiweaponchangelogMixinFields0 := changokushiweaponchangelogMixin[0].Fields()
	_ = changokushiweaponchangelogMixinFields0
	changokushiweaponchangelogFields := schema.ChangokushiWeaponChangeLog{}.Fields()
	_ = changokushiweaponchangelogFields
	// changokushiweaponchangelogDescCreatedAt is the schema descriptor for created_at field.
	changokushiweaponchangelogDescCreatedAt := changokushiweaponchangelogMixinFields0[0].Descriptor()
	// changokushiweaponchangelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	changokushiweaponchangelog.DefaultCreatedAt = changokushiweaponchangelogDescCreatedAt.Default.(func() time.Time)
	// changokushiweaponchangelogDescUpdatedAt is the schema descriptor for updated_at field.
	changokushiweaponchangelogDescUpdatedAt := changokushiweaponchangelogMixinFields0[1].Descriptor()
	// changokushiweaponchangelog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	changokushiweaponchangelog.DefaultUpdatedAt = changokushiweaponchangelogDescUpdatedAt.Default.(func() time.Time)
	// changokushiweaponchangelog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	changokushiweaponchangelog.UpdateDefaultUpdatedAt = changokushiweaponchangelogDescUpdatedAt.UpdateDefault.(func() time.Time)
}

const (
	Version = "v0.12.5"                                         // Version of ent codegen.
	Sum     = "h1:KREM5E4CSoej4zeGa88Ou/gfturAnpUv0mzAjch1sj4=" // Sum of ent codegen.
)
