// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LineNftsColumns holds the columns for the "line_nfts" table.
	LineNftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "line_nft_id", Type: field.TypeUint32},
		{Name: "contract_id", Type: field.TypeString},
		{Name: "token_type", Type: field.TypeString},
		{Name: "token_index", Type: field.TypeString},
		{Name: "token_name", Type: field.TypeString},
		{Name: "token_description", Type: field.TypeString, Size: 2147483647},
		{Name: "token_content_url", Type: field.TypeString},
	}
	// LineNftsTable holds the schema information for the "line_nfts" table.
	LineNftsTable = &schema.Table{
		Name:       "line_nfts",
		Comment:    "LINE NFT",
		Columns:    LineNftsColumns,
		PrimaryKey: []*schema.Column{LineNftsColumns[0]},
	}
	// LineNftActivitiesColumns holds the columns for the "line_nft_activities" table.
	LineNftActivitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "activity_type", Type: field.TypeString},
		{Name: "sale_id", Type: field.TypeUint32},
		{Name: "sale_type", Type: field.TypeString},
		{Name: "currency_type", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat32},
		{Name: "activated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "linenft_activities", Type: field.TypeUint32},
	}
	// LineNftActivitiesTable holds the schema information for the "line_nft_activities" table.
	LineNftActivitiesTable = &schema.Table{
		Name:       "line_nft_activities",
		Comment:    "LINE NFT 売買履歴",
		Columns:    LineNftActivitiesColumns,
		PrimaryKey: []*schema.Column{LineNftActivitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "line_nft_activities_line_nfts_activities",
				Columns:    []*schema.Column{LineNftActivitiesColumns[10]},
				RefColumns: []*schema.Column{LineNftsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LineNftMillionArthursPropertiesColumns holds the columns for the "line_nft_million_arthurs_properties" table.
	LineNftMillionArthursPropertiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "series", Type: field.TypeString, Nullable: true},
		{Name: "gear_category", Type: field.TypeString, Nullable: true},
		{Name: "gear_rarity", Type: field.TypeString, Nullable: true},
		{Name: "omj", Type: field.TypeString, Nullable: true},
		{Name: "linenft_million_arthurs_properties", Type: field.TypeUint32, Unique: true},
	}
	// LineNftMillionArthursPropertiesTable holds the schema information for the "line_nft_million_arthurs_properties" table.
	LineNftMillionArthursPropertiesTable = &schema.Table{
		Name:       "line_nft_million_arthurs_properties",
		Comment:    "LINE NFT 資産性ミリオンアーサーズのプロパティ",
		Columns:    LineNftMillionArthursPropertiesColumns,
		PrimaryKey: []*schema.Column{LineNftMillionArthursPropertiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "line_nft_million_arthurs_properties_line_nfts_million_arthurs_properties",
				Columns:    []*schema.Column{LineNftMillionArthursPropertiesColumns[8]},
				RefColumns: []*schema.Column{LineNftsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LineNftsTable,
		LineNftActivitiesTable,
		LineNftMillionArthursPropertiesTable,
	}
)

func init() {
	LineNftsTable.Annotation = &entsql.Annotation{
		Table: "line_nfts",
	}
	LineNftActivitiesTable.ForeignKeys[0].RefTable = LineNftsTable
	LineNftActivitiesTable.Annotation = &entsql.Annotation{
		Table: "line_nft_activities",
	}
	LineNftMillionArthursPropertiesTable.ForeignKeys[0].RefTable = LineNftsTable
	LineNftMillionArthursPropertiesTable.Annotation = &entsql.Annotation{
		Table: "line_nft_million_arthurs_properties",
	}
}
