// Code generated by ent, DO NOT EDIT.

package linenftactivity

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the linenftactivity type in the database.
	Label = "linenft_activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldActivityType holds the string denoting the activity_type field in the database.
	FieldActivityType = "activity_type"
	// FieldSaleID holds the string denoting the sale_id field in the database.
	FieldSaleID = "sale_id"
	// FieldSaleType holds the string denoting the sale_type field in the database.
	FieldSaleType = "sale_type"
	// FieldCurrencyType holds the string denoting the currency_type field in the database.
	FieldCurrencyType = "currency_type"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldActivatedAt holds the string denoting the activated_at field in the database.
	FieldActivatedAt = "activated_at"
	// EdgeLineNft holds the string denoting the line_nft edge name in mutations.
	EdgeLineNft = "line_nft"
	// Table holds the table name of the linenftactivity in the database.
	Table = "line_nft_activities"
	// LineNftTable is the table that holds the line_nft relation/edge.
	LineNftTable = "line_nft_activities"
	// LineNftInverseTable is the table name for the LINENFT entity.
	// It exists in this package in order to avoid circular dependency with the "linenft" package.
	LineNftInverseTable = "line_nfts"
	// LineNftColumn is the table column denoting the line_nft relation/edge.
	LineNftColumn = "linenft_activities"
)

// Columns holds all SQL columns for linenftactivity fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldActivityType,
	FieldSaleID,
	FieldSaleType,
	FieldCurrencyType,
	FieldPrice,
	FieldActivatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "line_nft_activities"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"linenft_activities",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/a10adotapp/a10a.app/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the LINENFTActivity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByActivityType orders the results by the activity_type field.
func ByActivityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityType, opts...).ToFunc()
}

// BySaleID orders the results by the sale_id field.
func BySaleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSaleID, opts...).ToFunc()
}

// BySaleType orders the results by the sale_type field.
func BySaleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSaleType, opts...).ToFunc()
}

// ByCurrencyType orders the results by the currency_type field.
func ByCurrencyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrencyType, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByActivatedAt orders the results by the activated_at field.
func ByActivatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivatedAt, opts...).ToFunc()
}

// ByLineNftField orders the results by line_nft field.
func ByLineNftField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLineNftStep(), sql.OrderByField(field, opts...))
	}
}
func newLineNftStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LineNftInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LineNftTable, LineNftColumn),
	)
}
