// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/a10adotapp/a10a.app/ent/changokushiweapon"
	"github.com/a10adotapp/a10a.app/ent/changokushiweaponchangelog"
	"github.com/a10adotapp/a10a.app/ent/predicate"
)

// ChangokushiWeaponQuery is the builder for querying ChangokushiWeapon entities.
type ChangokushiWeaponQuery struct {
	config
	ctx            *QueryContext
	order          []changokushiweapon.OrderOption
	inters         []Interceptor
	predicates     []predicate.ChangokushiWeapon
	withChangeLogs *ChangokushiWeaponChangeLogQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChangokushiWeaponQuery builder.
func (cwq *ChangokushiWeaponQuery) Where(ps ...predicate.ChangokushiWeapon) *ChangokushiWeaponQuery {
	cwq.predicates = append(cwq.predicates, ps...)
	return cwq
}

// Limit the number of records to be returned by this query.
func (cwq *ChangokushiWeaponQuery) Limit(limit int) *ChangokushiWeaponQuery {
	cwq.ctx.Limit = &limit
	return cwq
}

// Offset to start from.
func (cwq *ChangokushiWeaponQuery) Offset(offset int) *ChangokushiWeaponQuery {
	cwq.ctx.Offset = &offset
	return cwq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cwq *ChangokushiWeaponQuery) Unique(unique bool) *ChangokushiWeaponQuery {
	cwq.ctx.Unique = &unique
	return cwq
}

// Order specifies how the records should be ordered.
func (cwq *ChangokushiWeaponQuery) Order(o ...changokushiweapon.OrderOption) *ChangokushiWeaponQuery {
	cwq.order = append(cwq.order, o...)
	return cwq
}

// QueryChangeLogs chains the current query on the "change_logs" edge.
func (cwq *ChangokushiWeaponQuery) QueryChangeLogs() *ChangokushiWeaponChangeLogQuery {
	query := (&ChangokushiWeaponChangeLogClient{config: cwq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cwq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cwq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(changokushiweapon.Table, changokushiweapon.FieldID, selector),
			sqlgraph.To(changokushiweaponchangelog.Table, changokushiweaponchangelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, changokushiweapon.ChangeLogsTable, changokushiweapon.ChangeLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cwq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChangokushiWeapon entity from the query.
// Returns a *NotFoundError when no ChangokushiWeapon was found.
func (cwq *ChangokushiWeaponQuery) First(ctx context.Context) (*ChangokushiWeapon, error) {
	nodes, err := cwq.Limit(1).All(setContextOp(ctx, cwq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{changokushiweapon.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cwq *ChangokushiWeaponQuery) FirstX(ctx context.Context) *ChangokushiWeapon {
	node, err := cwq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChangokushiWeapon ID from the query.
// Returns a *NotFoundError when no ChangokushiWeapon ID was found.
func (cwq *ChangokushiWeaponQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = cwq.Limit(1).IDs(setContextOp(ctx, cwq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{changokushiweapon.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cwq *ChangokushiWeaponQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := cwq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChangokushiWeapon entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChangokushiWeapon entity is found.
// Returns a *NotFoundError when no ChangokushiWeapon entities are found.
func (cwq *ChangokushiWeaponQuery) Only(ctx context.Context) (*ChangokushiWeapon, error) {
	nodes, err := cwq.Limit(2).All(setContextOp(ctx, cwq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{changokushiweapon.Label}
	default:
		return nil, &NotSingularError{changokushiweapon.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cwq *ChangokushiWeaponQuery) OnlyX(ctx context.Context) *ChangokushiWeapon {
	node, err := cwq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChangokushiWeapon ID in the query.
// Returns a *NotSingularError when more than one ChangokushiWeapon ID is found.
// Returns a *NotFoundError when no entities are found.
func (cwq *ChangokushiWeaponQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = cwq.Limit(2).IDs(setContextOp(ctx, cwq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{changokushiweapon.Label}
	default:
		err = &NotSingularError{changokushiweapon.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cwq *ChangokushiWeaponQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := cwq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChangokushiWeapons.
func (cwq *ChangokushiWeaponQuery) All(ctx context.Context) ([]*ChangokushiWeapon, error) {
	ctx = setContextOp(ctx, cwq.ctx, "All")
	if err := cwq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChangokushiWeapon, *ChangokushiWeaponQuery]()
	return withInterceptors[[]*ChangokushiWeapon](ctx, cwq, qr, cwq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cwq *ChangokushiWeaponQuery) AllX(ctx context.Context) []*ChangokushiWeapon {
	nodes, err := cwq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChangokushiWeapon IDs.
func (cwq *ChangokushiWeaponQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if cwq.ctx.Unique == nil && cwq.path != nil {
		cwq.Unique(true)
	}
	ctx = setContextOp(ctx, cwq.ctx, "IDs")
	if err = cwq.Select(changokushiweapon.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cwq *ChangokushiWeaponQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := cwq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cwq *ChangokushiWeaponQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cwq.ctx, "Count")
	if err := cwq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cwq, querierCount[*ChangokushiWeaponQuery](), cwq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cwq *ChangokushiWeaponQuery) CountX(ctx context.Context) int {
	count, err := cwq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cwq *ChangokushiWeaponQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cwq.ctx, "Exist")
	switch _, err := cwq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cwq *ChangokushiWeaponQuery) ExistX(ctx context.Context) bool {
	exist, err := cwq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChangokushiWeaponQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cwq *ChangokushiWeaponQuery) Clone() *ChangokushiWeaponQuery {
	if cwq == nil {
		return nil
	}
	return &ChangokushiWeaponQuery{
		config:         cwq.config,
		ctx:            cwq.ctx.Clone(),
		order:          append([]changokushiweapon.OrderOption{}, cwq.order...),
		inters:         append([]Interceptor{}, cwq.inters...),
		predicates:     append([]predicate.ChangokushiWeapon{}, cwq.predicates...),
		withChangeLogs: cwq.withChangeLogs.Clone(),
		// clone intermediate query.
		sql:  cwq.sql.Clone(),
		path: cwq.path,
	}
}

// WithChangeLogs tells the query-builder to eager-load the nodes that are connected to
// the "change_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (cwq *ChangokushiWeaponQuery) WithChangeLogs(opts ...func(*ChangokushiWeaponChangeLogQuery)) *ChangokushiWeaponQuery {
	query := (&ChangokushiWeaponChangeLogClient{config: cwq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cwq.withChangeLogs = query
	return cwq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChangokushiWeapon.Query().
//		GroupBy(changokushiweapon.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cwq *ChangokushiWeaponQuery) GroupBy(field string, fields ...string) *ChangokushiWeaponGroupBy {
	cwq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChangokushiWeaponGroupBy{build: cwq}
	grbuild.flds = &cwq.ctx.Fields
	grbuild.label = changokushiweapon.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at"`
//	}
//
//	client.ChangokushiWeapon.Query().
//		Select(changokushiweapon.FieldCreatedAt).
//		Scan(ctx, &v)
func (cwq *ChangokushiWeaponQuery) Select(fields ...string) *ChangokushiWeaponSelect {
	cwq.ctx.Fields = append(cwq.ctx.Fields, fields...)
	sbuild := &ChangokushiWeaponSelect{ChangokushiWeaponQuery: cwq}
	sbuild.label = changokushiweapon.Label
	sbuild.flds, sbuild.scan = &cwq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChangokushiWeaponSelect configured with the given aggregations.
func (cwq *ChangokushiWeaponQuery) Aggregate(fns ...AggregateFunc) *ChangokushiWeaponSelect {
	return cwq.Select().Aggregate(fns...)
}

func (cwq *ChangokushiWeaponQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cwq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cwq); err != nil {
				return err
			}
		}
	}
	for _, f := range cwq.ctx.Fields {
		if !changokushiweapon.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cwq.path != nil {
		prev, err := cwq.path(ctx)
		if err != nil {
			return err
		}
		cwq.sql = prev
	}
	return nil
}

func (cwq *ChangokushiWeaponQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChangokushiWeapon, error) {
	var (
		nodes       = []*ChangokushiWeapon{}
		_spec       = cwq.querySpec()
		loadedTypes = [1]bool{
			cwq.withChangeLogs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChangokushiWeapon).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChangokushiWeapon{config: cwq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cwq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cwq.withChangeLogs; query != nil {
		if err := cwq.loadChangeLogs(ctx, query, nodes,
			func(n *ChangokushiWeapon) { n.Edges.ChangeLogs = []*ChangokushiWeaponChangeLog{} },
			func(n *ChangokushiWeapon, e *ChangokushiWeaponChangeLog) {
				n.Edges.ChangeLogs = append(n.Edges.ChangeLogs, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cwq *ChangokushiWeaponQuery) loadChangeLogs(ctx context.Context, query *ChangokushiWeaponChangeLogQuery, nodes []*ChangokushiWeapon, init func(*ChangokushiWeapon), assign func(*ChangokushiWeapon, *ChangokushiWeaponChangeLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint32]*ChangokushiWeapon)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(changokushiweaponchangelog.FieldChangokushiWeaponID)
	}
	query.Where(predicate.ChangokushiWeaponChangeLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(changokushiweapon.ChangeLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChangokushiWeaponID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "changokushi_weapon_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cwq *ChangokushiWeaponQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cwq.querySpec()
	_spec.Node.Columns = cwq.ctx.Fields
	if len(cwq.ctx.Fields) > 0 {
		_spec.Unique = cwq.ctx.Unique != nil && *cwq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cwq.driver, _spec)
}

func (cwq *ChangokushiWeaponQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(changokushiweapon.Table, changokushiweapon.Columns, sqlgraph.NewFieldSpec(changokushiweapon.FieldID, field.TypeUint32))
	_spec.From = cwq.sql
	if unique := cwq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cwq.path != nil {
		_spec.Unique = true
	}
	if fields := cwq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, changokushiweapon.FieldID)
		for i := range fields {
			if fields[i] != changokushiweapon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cwq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cwq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cwq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cwq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cwq *ChangokushiWeaponQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cwq.driver.Dialect())
	t1 := builder.Table(changokushiweapon.Table)
	columns := cwq.ctx.Fields
	if len(columns) == 0 {
		columns = changokushiweapon.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cwq.sql != nil {
		selector = cwq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cwq.ctx.Unique != nil && *cwq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cwq.predicates {
		p(selector)
	}
	for _, p := range cwq.order {
		p(selector)
	}
	if offset := cwq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cwq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChangokushiWeaponGroupBy is the group-by builder for ChangokushiWeapon entities.
type ChangokushiWeaponGroupBy struct {
	selector
	build *ChangokushiWeaponQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cwgb *ChangokushiWeaponGroupBy) Aggregate(fns ...AggregateFunc) *ChangokushiWeaponGroupBy {
	cwgb.fns = append(cwgb.fns, fns...)
	return cwgb
}

// Scan applies the selector query and scans the result into the given value.
func (cwgb *ChangokushiWeaponGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cwgb.build.ctx, "GroupBy")
	if err := cwgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChangokushiWeaponQuery, *ChangokushiWeaponGroupBy](ctx, cwgb.build, cwgb, cwgb.build.inters, v)
}

func (cwgb *ChangokushiWeaponGroupBy) sqlScan(ctx context.Context, root *ChangokushiWeaponQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cwgb.fns))
	for _, fn := range cwgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cwgb.flds)+len(cwgb.fns))
		for _, f := range *cwgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cwgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cwgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChangokushiWeaponSelect is the builder for selecting fields of ChangokushiWeapon entities.
type ChangokushiWeaponSelect struct {
	*ChangokushiWeaponQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cws *ChangokushiWeaponSelect) Aggregate(fns ...AggregateFunc) *ChangokushiWeaponSelect {
	cws.fns = append(cws.fns, fns...)
	return cws
}

// Scan applies the selector query and scans the result into the given value.
func (cws *ChangokushiWeaponSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cws.ctx, "Select")
	if err := cws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChangokushiWeaponQuery, *ChangokushiWeaponSelect](ctx, cws.ChangokushiWeaponQuery, cws, cws.inters, v)
}

func (cws *ChangokushiWeaponSelect) sqlScan(ctx context.Context, root *ChangokushiWeaponQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cws.fns))
	for _, fn := range cws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
