name: Deploy

on:
  workflow_dispatch:

permissions: write-all

jobs:
  migrate:
    uses: ./.github/workflows/deploy-migrations.yml
    secrets: inherit

  deploy:
    needs: migrate
    uses: ./.github/workflows/deploy-container.yml
    secrets: inherit
