name: Deploy

on:
  workflow_dispatch:

permissions: write-all

jobs:
  migrations:
    uses: ./.github/workflows/deploy-migrations.yml
    secrets: inherit

  container:
    needs: migrations
    uses: ./.github/workflows/deploy-container.yml
    secrets: inherit
