// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LINENFT is the predicate function for linenft builders.
type LINENFT func(*sql.Selector)

// LINENFTActivity is the predicate function for linenftactivity builders.
type LINENFTActivity func(*sql.Selector)

// LINENFTMillionArthursProperty is the predicate function for linenftmillionarthursproperty builders.
type LINENFTMillionArthursProperty func(*sql.Selector)
